development:
  adapter: postgresql
  encoding: unicode
  database: cribber_dev
  pool: 10
  username: postgres
  password: postgres

test:
  adapter: postgresql
  encoding: unicode
  database: cribber_test
  pool: 10
  username: postgres
  password: postgres

production:
  adapter: postgresql
  encoding: unicode
  database: cribber_production
  pool: 10
  username: postgres
  password: postgres

